import json

with open('ios/AiChing/Resources/hexagrams.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

vi_names = {
    0: "Khôn - Tiếp thụ", 1: "Phục - Hồi phục", 2: "Lâm - Đến gần",
    3: "Quán - Quan sát", 4: "Phệ hạp - Cắn xé", 5: "Bí - Trang sức",
    6: "Bác - Ly tán", 7: "Vô vọng - Thuần túy", 8: "Đại súc - Tích chứa",
    9: "Di - Nuôi dưỡng", 10: "Đại quá - Vượt quá", 11: "Khảm - Hiểm",
    12: "Ly - Bám vào", 13: "Hàm - Cảm ứng", 14: "Hằng - Bền lâu",
    15: "Độn - Thoái lui", 16: "Đại tráng - Đại dũng", 17: "Tấn - Tiến bộ",
    18: "Minh di - Ám muội", 19: "Gia nhân - Nhà", 20: "Khuê - Chống trái",
    21: "Kiển - Khó khăn", 22: "Giải - Thoát khỏi", 23: "Tổn - Giảm bớt",
    24: "Ích - Tăng thêm", 25: "Quải - Quyết đoán", 26: "Cấu - Gặp gỡ",
    27: "Tụy - Tụ họp", 28: "Thăng - Thăng tiến", 29: "Khốn - Cùng quẫn",
    30: "Tỉnh - Giếng", 31: "Cách - Cách mạng", 32: "Đỉnh - Đỉnh đồng",
    33: "Chấn - Kích động", 34: "Cấn - Ngừng nghỉ", 35: "Tiệm - Tiến triển",
    36: "Quy muội - Gả chồng", 37: "Phong - Phong phú", 38: "Lữ - Khách du",
    39: "Tốn - Nhu nhập", 40: "Đoài - Vui vẻ", 41: "Hoán - Phân tán",
    42: "Tiết - Tiết chế", 43: "Trung phục - Thành tín", 44: "Tiểu quá - Vượt nhỏ",
    45: "Ký tế - Đã xong", 46: "Vị tế - Chưa xong", 47: "Tụng - Kiện tụng",
    48: "Sư - Quân đội", 49: "Tỷ - Hợp nhau", 50: "Tiểu súc - Nuôi nhỏ",
    51: "Lý - Bước đi", 52: "Thái - Thái hòa", 53: "Bĩ - Bế tắc",
    54: "Đồng nhân - Đồng loại", 55: "Đại hữu - Sở hữu lớn",
    56: "Khiêm - Khiêm tốn", 57: "Dự - Vui vẻ", 58: "Tùy - Theo",
    59: "Cổ - Sửa đổi", 60: "Lâm - Rừng", 61: "Quán - Quan sát",
    62: "Hà - Sông", 63: "Càn - Sáng tạo"
}

vi_judgments = {
    0: "Khôn: Tiếp thụ đem lại thành công lớn lao, hanh thông nhờ sự bền bỉ của con ngựa cái.",
    1: "Phục: Ra vào không có lỗi. Bạn bè đến không có lỗi. Bảy ngày đến ngày hồi phục.",
    2: "Lâm có hanh thông lớn lao. Chính bền có lợi. Đến tháng thứ tám sẽ có tai họa.",
    3: "Quán: Lễ rước đã xong, chưa đến lễ dâng. Thành tín ngưỡng nhìn lên Ngài.",
    4: "Phệ hạp: Hanh thông. Xử lý công bằng thì tốt.",
    5: "Bí: Hanh thông. Việc nhỏ thì làm được lợi.",
    6: "Bác: Không đi đâu có lợi.",
    7: "Vô vọng: Hanh thông lớn. Chính bền có lợi. Không đúng đạo thì có họa.",
    8: "Đại súc: Chính bền có lợi. Không ăn ở nhà được tốt. Có thể vượt sông lớn.",
    9: "Di: Chính bền tốt. Xem sự nuôi dưỡng của mình.",
    10: "Đại quá: Nóc nhà cong xuống. Có nơi đến thì hanh thông.",
    11: "Khảm: Có lòng thành tín thì hanh thông trong lòng.",
    12: "Ly: Chính bền có lợi. Nuôi bò cái tốt.",
    13: "Hàm: Hanh thông. Chính bền tốt. Cưới vợ tốt.",
    14: "Hằng: Hanh thông. Không lỗi. Chính bền có lợi.",
    15: "Độn: Hanh thông. Việc nhỏ thì tốt.",
    16: "Đại tráng: Chính bền có lợi.",
    17: "Tấn: Quan công được thưởng nhiều ngựa. Một ngày tiếp kiến ba lần.",
    18: "Minh di: Gian nan nên giữ chính bền.",
    19: "Gia nhân: Sự bền chí của phụ nữ tốt.",
    20: "Khuê: Việc nhỏ tốt.",
    21: "Kiển: Hướng tây nam tốt. Hướng đông bắc không tốt.",
    22: "Giải: Hướng tây nam tốt. Không còn việc thì về tốt.",
    23: "Tổn: Có lòng thành tín thì đại cát. Có thể dùng hai chén nhỏ tế.",
    24: "Ích: Có việc làm tốt. Có thể vượt sông lớn.",
    25: "Quải: Kiên quyết trình bày. Có hiểm. Báo cho thành của mình.",
    26: "Cấu: Con gái mạnh mẽ. Không nên lấy cô ấy.",
    27: "Tụy: Hanh thông. Vua đến thái miếu. Gặp người lớn tốt.",
    28: "Thăng: Hanh thông lớn. Gặp người lớn. Đi về phía nam tốt.",
    29: "Khốn: Hanh thông. Chính bền. Người lớn mang lại tốt.",
    30: "Tỉnh: Thay đổi đời đời không thay đổi. Đến lui lấy nước.",
    31: "Cách: Đến ngày sẽ được tin. Đại hanh thông.",
    32: "Đỉnh: Đại cát. Hanh thông.",
    33: "Chấn: Hanh thông. Kinh đến! Sau cười ha ha!",
    34: "Cấn: Giữ lưng. Vào sân không thấy người.",
    35: "Tiệm: Gả con gái tốt. Chính bền tốt.",
    36: "Quy muội: Làm thì hung. Không có lợi.",
    37: "Phong: Hanh thông. Vua đạt phong. Đừng buồn.",
    38: "Lữ: Hanh thông trong việc nhỏ. Chính bền tốt.",
    39: "Tốn: Hanh thông nhỏ. Có nơi đến. Gặp người lớn.",
    40: "Đoài: Hanh thông. Chính bền tốt.",
    41: "Hoán: Hanh thông. Vua đến thái miếu. Có thể vượt sông.",
    42: "Tiết: Hanh thông. Tiết chế quá không tốt.",
    43: "Trung phục: Heo cá. Hanh thông. Vượt sông lớn.",
    44: "Tiểu quá: Hanh thông. Việc nhỏ làm được. Lớn không nên làm.",
    45: "Ký tế: Thành trong việc nhỏ. Đầu tốt cuối loạn.",
    46: "Vị tế: Hanh thông. Cáo nhỏ sắp qua sông.",
    47: "Tụng: Có lòng thành nhưng bị cản. Giữa đường dừng tốt.",
    48: "Sư: Quân cần chính bền và mạnh mẽ. Tốt không lỗi.",
    49: "Tỷ: Hợp nhau tốt. Người chậm trễ mang họa.",
    50: "Tiểu súc: Hanh thông. Mây dày không mưa từ miền tây.",
    51: "Lý: Bước đi trên đuôi cọp. Cọp không cắn. Hanh thông.",
    52: "Thái: Kẻ nhỏ đi, người lớn đến. Hanh thông.",
    53: "Bĩ: Kẻ xấu không tốt cho người quân tử. Lớn đi, nhỏ đến.",
    54: "Đồng nhân: Hanh thông. Vượt sông lớn. Chính bền tốt.",
    55: "Đại hữu: Đại hanh thông.",
    56: "Khiêm: Hanh thông. Người quân tử hoàn thành công việc.",
    57: "Dự: Có ích. Dựng tướng và xuất quân.",
    58: "Tùy: Đại hanh thông. Chính bền tốt. Không lỗi.",
    59: "Cổ: Đại hanh thông. Vượt sông lớn.",
    60: "Lâm: Tốt. Gặp người lớn thì hanh thông.",
    61: "Quán: Lễ rước đã xong nhưng chưa dâng lễ.",
    62: "Hà: Hanh thông. Vượt sông lớn.",
    63: "Càn: Hanh thông lớn, chính bền tốt.",
}

vi_images = {
    0: "Long đất tiếp thụ. Người quân tử có tấm lòng rộng rãi như đất, chứa đựng muôn vật.",
    1: "Hồi phục trong lòng đất. Vua chúa xưa đóng cửa ngày đông chí.",
    2: "Trên đất, dưới đầm. Người quân tử dạy không mệt mỏi.",
    3: "Gió trên đất. Vua xưa xem xét các nước.",
    4: "Sấm và chớp. Vua xưa đặt ra hình phạt rõ ràng.",
    5: "Lửa dưới chân núi. Người quân tử giải quyết việc hiện tại.",
    6: "Núi trên đất. Kẻ trên phải ban rộng cho kẻ dưới.",
    7: "Sấm dưới trời. Người quân tử thuận thiên nuôi dưỡng vạn vật.",
    8: "Trời trong núi. Người quân tử ôn cố tri tân.",
    9: "Chân núi sấm động. Người quân tử cẩn trọng ăn uống.",
    10: "Hồ trên cây. Người quân tử độc lập không ngại.",
    11: "Nước chảy không ngừng. Người quân tử đức bền.",
    12: "Ánh sáng hai lần. Người lớn rạng danh bốn phương.",
    13: "Núi và hồ. Người quân tử mở lòng đón nhận.",
    14: "Sấm và gió. Người quân tử đứng vững.",
    15: "Núi dưới trời. Người quân tử xa kẻ tiểu nhân.",
    16: "Sấm trên trời. Người quân tử không bước sai.",
    17: "Mặt trời mọc trên đất. Người quân tử sáng đức.",
    18: "Ánh sáng chìm vào đất. Người quân tử ẩn nhẫn.",
    19: "Gió trong lửa. Người quân tử xếp việc nhà.",
    20: "Lửa và hồ. Người quân tử hòa đồng.",
    21: "Nước trên núi. Người quân tử xét mình.",
    22: "Sấm và mưa. Người quân tử bỏ qua lỗi.",
    23: "Chân núi là hồ. Người quân tử kiềm chế dục vọng.",
    24: "Gió và sấm. Người quân tử thấy thiện thì noi theo.",
    25: "Hồ lên trời. Người quân tử ban rộng của cải.",
    26: "Gió dưới trời. Người quân tử ban hành mệnh lệnh.",
    27: "Hồ trên đất. Người quân tử sửa sang vũ khí.",
    28: "Cây mọc trong đất. Người quân tử thăng tiến nhờ đức.",
    29: "Hồ cạn nước. Người quân tử xả thân theo chí.",
    30: "Nước trên gỗ. Người quân tử khuyến khích nhân dân.",
    31: "Lửa trong hồ. Người quân tử đặt lịch.",
    32: "Lửa trên gỗ. Người quân tử củng cố mệnh.",
    33: "Sấm nối tiếp. Người quân tử tỉnh thức sửa lỗi.",
    34: "Núi liền núi. Người quân tử giữ tâm không vượt.",
    35: "Trên núi có cây. Người quân tử cư xử đúng đắn.",
    36: "Sấm trên hồ. Người quân tử biết lẽ vô thường.",
    37: "Sấm chớp cùng đến. Người quân tử xét xử công minh.",
    38: "Lửa trên núi. Người quân tử cẩn thận hình phạt.",
    39: "Gió theo gió. Người quân tử truyền lệnh.",
    40: "Hồ trên nhau. Người quân tử cùng bạn học tập.",
    41: "Gió trên nước. Vua xưa tế thần lập tông miếu.",
    42: "Trên hồ là nước. Người quân tử đặt ra đo lường.",
    43: "Gió trên hồ. Người quân tử hoãn thi hành án.",
    44: "Sấm trên núi. Người quân tử cô đơn nhưng vô úy.",
    45: "Nước trên lửa. Người quân tử phòng ngừa suy vi.",
    46: "Lửa trên nước. Người quân tử phân biệt vạn vật.",
    47: "Trời nước trái chiều. Người quân tử cân nhắc.",
    48: "Giữa đất có nước. Người quân tử nuôi dân.",
    49: "Nước trên đất. Vua xưa chia đất phong hầu.",
    50: "Gió trên trời. Người quân tử tu chỉnh oai nghi.",
    51: "Trời trên hồ. Người quân tử phân biệt cao thấp.",
    52: "Trời đất giao hòa. Vua hoàn thành trời đất.",
    53: "Trời đất không giao. Người quân tử lui về nội tâm.",
    54: "Trời và lửa. Người quân tử tổ chức xã hội.",
    55: "Lửa trên trời. Người quân tử diệt ác dương thiện.",
    56: "Trong đất có núi. Người quân tử giảm bớt cái thừa.",
    57: "Sấm từ đất. Vua xưa làm nhạc.",
    58: "Sấm trong hồ. Người quân tử về nghỉ.",
    59: "Gió dưới núi. Người quân tử cổ vũ nhân dân.",
    63: "Trời chuyển động. Người quân tử tự cường."
}

for hex in data['hexagrams']:
    hid = hex['id']
    hex['nameVi'] = vi_names.get(hid, hex['name'])
    hex['judgmentVi'] = vi_judgments.get(hid, hex['judgment'])
    hex['imageVi'] = vi_images.get(hid, hex['image'])
    hex['lineTextsVi'] = None

with open('ios/AiChing/Resources/hexagrams.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

count = sum(1 for h in data['hexagrams'] if h.get('nameVi'))
print(f'OK: {count}/64 hexagrams have Vietnamese names')
print(f'Total hexagrams: {len(data["hexagrams"])}')
