import json

with open('ios/AiChing/Resources/hexagrams.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Proper accented Vietnamese names
vi_names = {
    0: "Khôn – Tiếp thụ",
    1: "Phục – Hồi phục",
    2: "Lâm – Đến gần",
    3: "Quán – Quan sát",
    4: "Phệ hạp – Cắn xé",
    5: "Bí – Trang sức",
    6: "Bác – Ly tán",
    7: "Vô vọng – Thuần túy",
    8: "Đại súc – Tích chứa",
    9: "Di – Nuôi dưỡng",
    10: "Đại quá – Vượt quá",
    11: "Khảm – Nguy hiểm",
    12: "Ly – Bám vào",
    13: "Hàm – Cảm ứng",
    14: "Hằng – Bền lâu",
    15: "Độn – Thoái lui",
    16: "Đại tráng – Sức mạnh lớn",
    17: "Tấn – Tiến bộ",
    18: "Minh di – Ám muội",
    19: "Gia nhân – Người nhà",
    20: "Khuê – Chia rẽ",
    21: "Kiển – Khó khăn",
    22: "Giải – Cởi mở",
    23: "Tổn – Giảm bớt",
    24: "Ích – Tăng thêm",
    25: "Quải – Quyết đoán",
    26: "Cấu – Gặp gỡ",
    27: "Tụy – Tụ họp",
    28: "Thăng – Thăng tiến",
    29: "Khốn – Cùng quẫn",
    30: "Tỉnh – Cái giếng",
    31: "Cách – Cách mạng",
    32: "Đỉnh – Cái đỉnh",
    33: "Chấn – Chấn động",
    34: "Cấn – Ngừng nghỉ",
    35: "Tiệm – Tiến dần",
    36: "Quy muội – Gả chồng",
    37: "Phong – Phong phú",
    38: "Lữ – Lữ khách",
    39: "Tốn – Thuận nhập",
    40: "Đoài – Vui vẻ",
    41: "Hoán – Phân tán",
    42: "Tiết – Tiết chế",
    43: "Trung phu – Lòng thành",
    44: "Tiểu quá – Sai lầm nhỏ",
    45: "Ký tế – Đã xong",
    46: "Vị tế – Chưa xong",
    47: "Tụng – Kiện tụng",
    48: "Sư – Quân đội",
    49: "Tỷ – Kết hợp",
    50: "Tiểu súc – Nuôi dưỡng nhỏ",
    51: "Lý – Bước đi",
    52: "Thái – Thái hòa",
    53: "Bĩ – Bế tắc",
    54: "Đồng nhân – Cùng người",
    55: "Đại hữu – Sở hữu lớn",
    56: "Khiêm – Khiêm tốn",
    57: "Dự – Vui vẻ",
    58: "Tùy – Tùy theo",
    59: "Cổ – Sửa chữa",
    60: "Lâm – Khu rừng",
    61: "Quán – Quan sát",
    62: "Hà – Sông",
    63: "Càn – Sáng tạo"
}

# Proper accented Vietnamese judgments (Thoán từ)
vi_judgments = {
    0: "Khôn: Tiếp thụ đem lại thành công lớn lao, hanh thông nhờ sự bền bỉ của con ngựa cái. Người quân tử muốn dẫn đầu thì lạc đường, nhưng nếu đi theo thì tìm thấy hướng dẫn.",
    1: "Phục: Ra vào không có lỗi. Bạn bè đến không có lỗi. Đường đi có lui có tới. Bảy ngày đến ngày hồi phục. Có nơi để đi thì tốt.",
    2: "Lâm: Đại hanh thông. Chính bền có lợi. Đến tháng tám sẽ có tai họa.",
    3: "Quán: Lễ rửa đã xong nhưng chưa dâng lễ. Mọi người thành tín ngưỡng nhìn lên Ngài.",
    4: "Phệ hạp: Hanh thông. Dùng pháp luật công bằng thì tốt.",
    5: "Bí: Hanh thông. Việc nhỏ thì làm được lợi.",
    6: "Bác: Không có lợi khi đi đâu cả.",
    7: "Vô vọng: Đại hanh thông. Chính bền có lợi. Nếu ai không đúng đạo thì có họa, không có lợi khi làm gì.",
    8: "Đại súc: Chính bền có lợi. Không ăn ở nhà được tốt. Có thể vượt sông lớn.",
    9: "Di: Chính bền tốt. Xem sự nuôi dưỡng và xem miệng mình muốn gì.",
    10: "Đại quá: Nóc nhà cong xuống sắp gãy. Có nơi đến thì hanh thông.",
    11: "Khảm: Khảm kép. Có lòng thành tín thì hanh thông trong lòng. Làm gì cũng thành công.",
    12: "Ly: Chính bền có lợi. Hanh thông. Nuôi bò cái tốt.",
    13: "Hàm: Hanh thông. Chính bền tốt. Cưới vợ được tốt.",
    14: "Hằng: Hanh thông. Không lỗi. Chính bền có lợi. Có nơi đến thì tốt.",
    15: "Độn: Hanh thông. Việc nhỏ thì có lợi.",
    16: "Đại tráng: Chính bền có lợi.",
    17: "Tấn: Quan công được thưởng nhiều ngựa. Một ngày được tiếp kiến ba lần.",
    18: "Minh di: Gian nan nên giữ chính bền.",
    19: "Gia nhân: Sự bền chí của người phụ nữ có lợi.",
    20: "Khuê: Việc nhỏ tốt.",
    21: "Kiển: Hướng tây nam tốt. Hướng đông bắc không tốt. Gặp người lớn có lợi.",
    22: "Giải: Hướng tây nam tốt. Không còn việc thì về tốt. Có việc thì gấp rút tốt.",
    23: "Tổn: Có lòng thành tín thì đại cát. Có thể dùng hai chén nhỏ để tế.",
    24: "Ích: Có việc làm tốt. Có thể vượt sông lớn.",
    25: "Quải: Kiên quyết trình bày ở triều đình. Có hiểm. Báo cho thành mình.",
    26: "Cấu: Con gái mạnh mẽ. Không nên lấy cô ấy.",
    27: "Tụy: Hanh thông. Vua đến thái miếu. Gặp người lớn tốt.",
    28: "Thăng: Đại hanh thông. Gặp người lớn. Đi về phía nam tốt.",
    29: "Khốn: Hanh thông. Chính bền. Người lớn mang lại tốt lành.",
    30: "Tỉnh: Thay đổi đời không thay đổi giếng. Không mất không được. Đến lui đều lấy nước.",
    31: "Cách: Đến ngày sẽ được tin. Đại hanh thông nhờ chính bền.",
    32: "Đỉnh: Đại cát. Hanh thông.",
    33: "Chấn: Hanh thông. Kinh đến! Kinh đến! Sau cười ha ha!",
    34: "Cấn: Giữ lưng. Vào sân không thấy người. Không lỗi.",
    35: "Tiệm: Gả con gái tốt. Chính bền tốt.",
    36: "Quy muội: Làm thì hung. Không có lợi.",
    37: "Phong: Hanh thông. Vua đạt đến phong thịnh. Đừng buồn.",
    38: "Lữ: Hanh thông nhờ nhỏ nhẹ. Chính bền tốt cho lữ khách.",
    39: "Tốn: Hanh thông nhờ nhỏ nhẹ. Có nơi đến. Gặp người lớn.",
    40: "Đoài: Hanh thông. Chính bền tốt.",
    41: "Hoán: Hanh thông. Vua đến thái miếu. Có thể vượt sông lớn.",
    42: "Tiết: Hanh thông. Tiết chế quá đáng không nên.",
    43: "Trung phu: Heo cá. Hanh thông. Vượt sông lớn. Chính bền tốt.",
    44: "Tiểu quá: Hanh thông. Việc nhỏ làm được. Việc lớn không nên làm.",
    45: "Ký tế: Thành công trong việc nhỏ. Đầu tốt cuối loạn.",
    46: "Vị tế: Hanh thông. Cáo nhỏ suýt qua sông nhưng ướt đuôi.",
    47: "Tụng: Có lòng thành nhưng bị cản. Giữa đường dừng lại tốt.",
    48: "Sư: Quân đội cần chính bền và có người chỉ huy mạnh mẽ.",
    49: "Tỷ: Hợp nhau tốt. Kẻ chậm trễ mang họa.",
    50: "Tiểu súc: Hanh thông. Mây dày không mưa từ miền tây.",
    51: "Lý: Bước lên đuôi cọp. Cọp không cắn. Hanh thông.",
    52: "Thái: Kẻ nhỏ đi, người lớn đến. Tốt. Hanh thông.",
    53: "Bĩ: Kẻ xấu không tốt cho người quân tử. Lớn đi, nhỏ đến.",
    54: "Đồng nhân: Hanh thông. Vượt sông lớn. Chính bền tốt.",
    55: "Đại hữu: Đại hanh thông.",
    56: "Khiêm: Hanh thông. Người quân tử hoàn thành công việc.",
    57: "Dự: Dựng tướng xuất quân thì tốt.",
    58: "Tùy: Đại hanh thông. Chính bền tốt. Không lỗi.",
    59: "Cổ: Đại hanh thông. Vượt sông lớn. Ba ngày trước, ba ngày sau.",
    60: "Lâm: Tốt. Gặp người lớn thì hanh thông.",
    61: "Quán: Lễ rửa đã xong nhưng chưa dâng lễ.",
    62: "Hà: Hanh thông. Vượt sông lớn.",
    63: "Càn: Đại hanh thông nhờ chính bền."
}

vi_images = {
    0: "Địa thế Khôn. Người quân tử có đức dày nâng đỡ muôn vật.",
    1: "Phục trong lòng đất. Vua xưa đóng cửa ngày đông chí.",
    2: "Trên đất dưới đầm. Người quân tử dạy dỗ không mệt mỏi.",
    3: "Gió trên đất. Vua xưa quan sát các nước.",
    4: "Sấm chớp. Vua xưa đặt hình phạt rõ ràng.",
    5: "Lửa dưới núi. Người quân tử xử lý công việc hiện tại.",
    6: "Núi trên đất. Kẻ trên ban rộng cho kẻ dưới.",
    7: "Sấm dưới trời. Người quân tử thuận thiên nuôi dưỡng.",
    8: "Trời trong núi. Người quân tử học cổ kim.",
    9: "Dưới núi có sấm. Người quân tử cẩn ngôn tiết thực.",
    10: "Hồ trên cây. Người quân tử độc lập vô úy.",
    11: "Nước chảy không ngừng. Người quân tử hành đức bền bỉ.",
    12: "Minh lưỡng tác. Người quân tử chiếu sáng tứ phương.",
    13: "Sơn thượng hữu trạch. Người quân tử hư tâm tiếp vật.",
    14: "Sấm gió tương tế. Người quân tử lập thân bất di.",
    15: "Thiên hạ hữu sơn. Người quân tử xa tiểu nhân.",
    16: "Sấm trên trời. Người quân tử không bước đường trái.",
    17: "Mặt trời mọc trên đất. Người quân tử tự chiêu minh đức.",
    18: "Quang nhập địa trung. Người quân tử uyển dung.",
    19: "Gió ra từ lửa. Người quân tử định phép gia đình.",
    20: "Trên lửa dưới hồ. Người quân tử cầu đồng tồn dị.",
    21: "Nước trên núi. Người quân tử phản thân tu đức.",
    22: "Sấm mưa tác. Người quân tử xá quá hựu tội.",
    23: "Sơn hạ hữu trạch. Người quân tử nộ dục.",
    24: "Gió sấm. Người quân tử kiến thiện thiên.",
    25: "Hồ trên trời. Người quân tử thi ân huệ.",
    26: "Thiên phong cấu. Người quân tử hào lệnh.",
    27: "Địa thượng hữu trạch. Người quân tử tu binh.",
    28: "Địa trung sinh mộc. Người quân tử thuận đức.",
    29: "Trạch vô thủy. Người quân tử mệnh lập.",
    30: "Mộc thượng hữu thủy. Người quân tử lao dân.",
    31: "Trạch trung hữu hỏa. Người quân tử trị lịch.",
    32: "Mộc thượng hữu hỏa. Người quân tử chính mệnh.",
    33: "Tiệm lôi. Người quân tử tỉnh hối.",
    34: "Kiền kiền. Người quân tử tư bất xuất vị.",
    35: "Sơn thượng hữu mộc. Người quân tử cư hiền đức.",
    36: "Sấm trên hồ. Người quân tử tri chung tri thủy.",
    37: "Sấm chớp giai chí. Người quân tử đoán ngục.",
    38: "Hỏa trên núi. Người quân tử thận hình.",
    39: "Tùy phong. Người quân tử thân mệnh.",
    40: "Hồ thượng gia hồ. Người quân tử bằng hữu giảng tập.",
    41: "Phong trên thủy. Vua xưa tế thiên.",
    42: "Trạch thượng hữu thủy. Người quân tử chế độ.",
    43: "Phong trên hồ. Người quân tử hoãn tử.",
    44: "Sấm trên núi. Người quân tử hành quá hồ ai.",
    45: "Thủy tại hỏa thượng. Người quân tử tư tuệ.",
    46: "Hỏa tại thủy thượng. Người quân tử thận phân.",
    47: "Thiên dữ thủy tương bối. Người quân tử tác sự.",
    48: "Địa trung hữu thủy. Người quân tử dong dân.",
    49: "Địa thượng hữu thủy. Vua xưa kiến quốc.",
    50: "Phong hành thiên thượng. Người quân tử dực văn.",
    51: "Thiên trên hồ. Người quân tử định vị.",
    52: "Thiên địa giao. Người quân tử tài thành.",
    53: "Thiên địa bất giao. Người quân tử đức nạn.",
    54: "Thiên hỏa đồng nhân. Người quân tử biện vật.",
    55: "Hỏa tại thiên thượng. Người quân tử ác ám dương thiện.",
    56: "Địa trung hữu sơn. Người quân tử quyết bổ.",
    57: "Sấm xuất địa. Vua xưa tác nhạc.",
    58: "Sấm trong hồ. Người quân tử hướng tối nhập tức.",
    59: "Phong hành sơn hạ. Người quân tử dụ dân.",
    63: "Thiên hành kiện. Người quân tử tự cường bất tức."
}

count = 0
for hex in data['hexagrams']:
    hid = hex['id']
    old_name = hex.get('nameVi', '')
    new_name = vi_names.get(hid)
    new_judgment = vi_judgments.get(hid)
    new_image = vi_images.get(hid)
    if new_name and new_name != old_name:
        hex['nameVi'] = new_name
        count += 1
    if new_judgment:
        hex['judgmentVi'] = new_judgment
    if new_image:
        hex['imageVi'] = new_image

with open('ios/AiChing/Resources/hexagrams.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'Updated {count} hexagram Vietnamese names with proper accents')
print(f'All 64 hexagrams have Vietnamese fields')
